---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest
  customize:
    memory: 384

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box

suites:
- name: redis
  run_list:
  - recipe[redisio::default]
  - recipe[redisio::enable]
  attributes: {
    "redisio": {
      "servers": [{
        "port": "6379"
        }]
    }
  }
- name: sentinel
  run_list:
  - recipe[redisio::sentinel]
  - recipe[redisio::sentinel_enable]
  attributes: {
    "redisio": {
      "sentinels": [{
        "sentinel_port": "26379",
        "name": "redisio",
        "master_port": "6379"
        }]
    }
  }